version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  ms-ticket-manager:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      SPRING_DATA_MONGODB_DATABASE: db_ticket
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 15s
      retries: 20
      start_period: 30s

  mongodb:
    container_name: "db_ticket"
    image: "mongodb/mongodb-community-server:7.0.0-ubi8"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u admin -p admin --eval
      interval: 10s
      timeout: 15s
      retries: 20
      start_period: 30s