version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  ms-event-manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      SPRING_DATA_MONGODB_DATABASE: db_event
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
  mongodb:
    container_name: "db_event"
    image: "mongodb/mongodb-community-server:7.0.0-ubi8"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u admin -p admin --eval
      interval: 10s
      timeout: 15s
      retries: 20
      start_period: 30s