spring:
  application:
    name: ms-ticket-manager
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:admin}:${MONGODB_PASSWORD:admin}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27018}
      database: ${DB_NAME:db_ticket}
      authentication-database: ${AUTH_DB:admin}
  rabbitmq:
    host: ${RABBITMQ-HOST:localhost}
    port: ${RABBITMQ-PORT:5672}
    username: ${RABBITMQ-USERNAME:guest}
    password: ${RABBITMQ-PASSWORD:guest}

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/v1/tickets/api-docs
  packagesToScan: com.johann.msticketmanager.web.controller

mq:
  queue:
    send-email: send-email
